name: QA

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'deploy/QA**'
      - 'develop'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
        
      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
          
      - name: Install Dependencies
        run: yarn install
        
      - name: Print yarn version
        run: yarn -v
        
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./gitub_action_key
          sudo chmod 600 ./gitub_action_key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
